### ISSUE TITLE
column_patch

### ISSUE THREAD

**Issue by siduck** [BeyondMagic/st#1]
Hi @BeyondMagic  , I tried your build and resizing doesnt cut any content inside the terminal window . Could you share the column_patch patch? It'd be really helpfull , I'd patch it on my st build :)

**Comment by siduck** [comment]
Also wouldnt it be better if you used the same bg color as terminal's for this blue , so it wouldnt be visible :D

![image](https://user-images.githubusercontent.com/59060246/121546480-f30ab580-ca28-11eb-8f5d-8ead0d21de05.png)

**Comment by BeyondMagic** [comment]
Oh boy...

My computer died a few weeks ago, you can see by profile's commits history.

You have two options, then, see the last few commits where the rezise function of st.c is changed, and there try to copy it, or just wait some time when I have back my computer and the patch for columns and rows separated in a diff.

**Comment by BeyondMagic** [comment]
> Also wouldnt it be better if you used the same bg color as terminal's for this blue , so it wouldnt be visible :D

Yep, will make it.

**Comment by siduck** [comment]
> My computer died a few weeks ago, you can see by profile's commits history.
 
these are the only commits for the patch right?

![image](https://user-images.githubusercontent.com/59060246/121551238-19325480-ca2d-11eb-982b-a9ab492a8d85.png)

**Comment by siduck** [comment]
I patched diffs from those 3 commits , it works but now I get this Segmentation fault error :c

**Comment by siduck** [comment]
nvm I forgot to see the latest commit regarding it 

![image](https://user-images.githubusercontent.com/59060246/121559641-6534c780-ca34-11eb-9925-57b0a541ced1.png)

on my way!

**Comment by siduck** [comment]
I patched it now , it works but 

- whenever I open the terminal and try "scroll forward" first, the terminal force exits itself (segmentation fault) 
- but if I try "scroll backward" + "scroll forward" then the terminal doesnt exit itself 

[changes made](https://github.com/siduck76/st/commit/8bbb1fe945cab5ffae1499f80d2e2490f8ab4a02)

If you want to test this build 

git clone https://github.com/siduck76/st --branch test

**Comment by BeyondMagic** [comment]
I believe col and term.col are set in my build, going to give a look.

I'll help you eventually with it, I just can't right now, sorry.

**Comment by siduck** [comment]
are these the only column_patch changes you've made?

![image](https://user-images.githubusercontent.com/59060246/121621791-7dcfcc80-ca8a-11eb-90e2-42d3d9a3caa3.png)

**Comment by BeyondMagic** [comment]
```
 st.c st.h x.c: rows and columns patch

Patch extracted from https://github.com/ashish-yadav11/st

NOTE: Patch is applied on a st build with other patches on it, a few to
name are liga/boxdraw/hist_scroll patch, however it's not that hard to
actually make this fit on a unpatched st..., it just take time.

Almost every change there is necessary for the patch to work, so you
can replace the history_scroll patch with this one without fear because
the patch includes both row and columns memory resizing.
```
https://github.com/BeyondMagic/st/blob/01d7a9dc04203f6fe2410413a038ac1f6c4515fb/column-rows-patch-st-with-liga-box-hist.diff
