### ISSUE TITLE
boxdraw conflicts with columns patch

### ISSUE THREAD

**Issue by sewnie** [BeyondMagic/st#3]
```
/bin/ld: boxdraw.o: warning: relocation against `boxdraw_bold' in read-only section `.text'
/bin/ld: boxdraw.o: in function `isboxdraw':
boxdraw.c:(.text+0x23): undefined reference to `boxdraw'
/bin/ld: boxdraw.c:(.text+0x34): undefined reference to `boxdraw_braille'
/bin/ld: boxdraw.o: in function `boxdrawindex':
boxdraw.c:(.text+0x66): undefined reference to `boxdraw_braille'
/bin/ld: boxdraw.c:(.text+0x7d): undefined reference to `boxdraw_bold'
/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
make: *** [Makefile:31: st] Error 1
```

**Comment by BeyondMagic** [comment]
You'll have to give me more than this to help you... what are you exactly trying to do? I can think of two things:

1. You're trying to compile this repository and it is failing.
2. You patched [this file](https://github.com/BeyondMagic/st/blob/master/patches/columns-rows-reflow-st-unpatched-new.patch) into your st build and it is failing to compile.

Be aware that if you're trying to patch anything you should resolve the conflicts; and that by itself boxdraw or the columns patch doesn't have any conflict with each other, but the lines that the patch changes may conflict.

**Comment by sewnie** [comment]
its fixed cause i started st from git source and boxdraw + scrollback works thanks
also thanks for the patch
