### ISSUE TITLE
No font or letter are displayed on terminal

### ISSUE THREAD

**Issue by orangethewell** [BeyondMagic/st#5]
The terminal doesn't display any letter on screen. I don't know if it because of using Manjaro instead of Arch, but since I tried the last time with all fonts configured, it just doesn't display any font or letter on a blue transparent screen. (Therefore, it isn't a error with picom, killing it doesn't change anything)

**Comment by BeyondMagic** [comment]
You need to set fonts you have in your system so that it can render properly.

Use `fc-list` to see the fonts you have and edit `config.h` file to change that configuration, or use _XResources_ with the `flarity.fonts` option key to set fonts dynamically.
