### ISSUE TITLE
box draw issue

### ISSUE THREAD

**Issue by Zerogaku** [BeyondMagic/st#6]
hey i've been searching for an alternative to luke smith's st build since it had no scrollback reflow and i stumbled across yours and really liked the reflow implementation, one issue though, i noticed the boxdraw seems a little incomplete?

here's and image from flarity:
![image](https://github.com/BeyondMagic/flarity/assets/144664603/be2f309a-4f09-4e15-9c2c-87d4a31d36a8)

and here's and image from luke smith's st for comparision:
![image](https://github.com/BeyondMagic/flarity/assets/144664603/a62c7c54-c0e2-4878-b779-f54adeef9455)

and yes i did enable boxdraw in the config, i even tried to enable the rest to see if it will do something as well
![image](https://github.com/BeyondMagic/flarity/assets/144664603/f415c8c2-022e-470b-ba7b-c4e8bd892923)

i'm not sure if it has something to do with the specific version of boxdraw or because of ligatures needing a special version to work with boxdraw.

also may i ask what version of st is currently being used for flarity?

**Comment by BeyondMagic** [comment]
I think the problem has to do with height and width of each character. There's two lines on the `config.h`, and `flarity.x` if you're using it, that can change this behaviour:

![image](https://github.com/BeyondMagic/flarity/assets/51831435/39327d64-5a05-4d6a-8347-1ebed11a1478)

Try making them smaller, and checking the size of your old ST build.

> also may i ask what version of st is currently being used for flarity?

No idea, though I think Sunday I can update it to the latest version.

**Comment by Zerogaku** [comment]
ok so both configurations have cwscale and chscale set to 1, just that flarity seem to have missing space, because after fiddling around, setting 0.83 manages to close the space between the characters, but now they're being squished or cut off:

for flarity ampersand tilde and the m at the end are being cut off
![image](https://github.com/BeyondMagic/flarity/assets/144664603/18627def-0702-4efc-b2f9-9fb452309dc0)
![image](https://github.com/BeyondMagic/flarity/assets/144664603/4eab8c3e-203f-42cf-9ae2-56eaa566b6cf)


while the old st build looks normal
![image](https://github.com/BeyondMagic/flarity/assets/144664603/6693f1d5-f8e1-4f8c-9fd4-2167208ee2ef)
![image](https://github.com/BeyondMagic/flarity/assets/144664603/8f63f134-a2f3-4f37-8653-e06aac42d925)


i'm starting to think it has to do with the way i set up the font, I'm using jetbrainsmono nerdfont and i set it in the Xresources file and the config.h for flarity.

config.h for flarity:
![image](https://github.com/BeyondMagic/flarity/assets/144664603/58fc92df-3aa2-4ac7-8d6b-9594f64573ef)
xresources:
![image](https://github.com/BeyondMagic/flarity/assets/144664603/f8dd0f70-397b-4073-be8e-f41c5596dc2d)

**Comment by BeyondMagic** [comment]
Sorry, I have no idea how to fix this... I'm archiving this repository since I've moved to Wayland, and I'd recommend the same.
